name: Run Tests

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*' # Ignore pushes to tags
  pull_request:
    branches:
      - '*' # Run on all branches for pull requests

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: Run Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up your environment and dependencies here (e.g., installing Node.js)

      - name: Install dependencies
        run: npm install

      # Run your tests
      - name: Run tests
        run: npm run test